package main

import (
	"log"

	"github.com/gin-gonic/gin"
	"github.com/joho/godotenv"
	"github.com/robfig/cron/v3"
	"hrms_backend/internal/config"
	"hrms_backend/internal/controllers"
	"hrms_backend/internal/cronJob"
	"hrms_backend/internal/repository"
	"hrms_backend/internal/services"

	docs "hrms_backend/docs" // docs is generated by Swag CLI
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

// @title           HRMS System API
// @version         1.0
// @description     A minimal HRMS API for managing students and their attendance.
// @termsOfService  http://swagger.io/terms/

// @contact.name   API Support
// @contact.url    https://www.linkedin.com/in/muhammad-talha-nasir-8a5428219/
// @contact.email  talhanasir.business@gmail.com

// @license.name  MIT
// @license.url   https://opensource.org/licenses/MIT

// @host      localhost:8080
// @BasePath  /
func main() {
	// load env
	err := godotenv.Load()
	if err != nil {
		log.Println("Warning: No .env file found (relying on system env vars)")
	}

	// Connect to db
	config.ConnectDB()

	// Initialize the Router
	r := gin.Default()

	// Swagger endpoint
	docs.SwaggerInfo.BasePath = "/"
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// first Repository (Talks to DB)
	// internal/repository/student_repository.go
	studentRepo := repository.NewStudentRepository(config.DB)
	attendanceRepo := repository.NewAttendanceRepository(config.DB)

	// Service (Talks to Repository)
	// internal/services/student_service.go
	studentService := services.NewStudentService(studentRepo)
	attendanceService := services.NewAttendanceService(attendanceRepo, studentRepo)
	// Controller (Talks to Service)
	// internal/controllers/student_controller.go
	studentController := controllers.NewStudentController(studentService)
	attendanceController := controllers.NewAttendanceController(attendanceService)
	// Create : http://localhost:8080/students
	studentGroup := r.Group("/students")
	attendanceGroup := r.Group("/attendance")
	// Pass the group to the controller so it can define endpoints
	studentController.RegisterRoutes(studentGroup)
	attendanceController.RegisterRoutes(attendanceGroup)

	c := cron.New()
	attendanceCron := cronJob.NewAttendanceCron(attendanceService)

	// Schedule: Run every minute for testing purposes ("@every 1m")
	// For actual weekly: "@weekly" or "0 0 * * 0" (Sunday midnight)
	_, err = c.AddFunc("@every 1m", attendanceCron.RunWeeklyReport)
	if err != nil {
		log.Fatal("Failed to add cron job:", err)
	}
	c.Start()
	log.Println("⏳ Cron Scheduler started...")

	// Start the server
	log.Println("Server starting on port 8080...")
	if err := r.Run(":8080"); err != nil {
		log.Fatal("Failed to run server: ", err)
	}
}
